### ISSUE TITLE
It doesn't find audacious' plugin directory automatically

### ISSUE THREAD

**Issue by HybridDog** [cspiegel/audacious-openmpt#1]
When installing, the Input folder is created at / (top of the file system) because it doesn't find the directory.
`$ pkg-config audacious --var=plugin_dir` says
 *Unknown option --var=plugin_dir*

The plugin folder is at /usr/lib/x86_64-linux-gnu/audacious, from the package audacious-plugins. When l specify it manually with DESTDIR, it works.

**Comment by cspiegel** [comment]
Thanks for the report.  This was due to a difference between pkgconf (which I use locally) and pkg-config.  I've updated the build system to use a flag that both pkgconf and pkg-config understand, so it should work now.

**Comment by HybridDog** [comment]
Seems to work, thanks.
